Updated pre-commit to show line that contains the fixme.

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -1,9 +1,9 @@
 #!/bin/sh
-
-if git diff --cached | grep '^\+' | grep -q 'FIXME'; then
-    echo "ERROR: Cannot commit forbidden word 'FIXME'" >&2
-    echo "If you know what you are doing you can ignore this temporarily with --no-verify" >&2
-    echo "If you want to modify this behavior permanently, see .git/hooks/pre-commit" >&2
-    exit 1  # reject
+exec 1>&2
+FORBIDDEN_RE="[Ff][Ii][Xx][Mm][Ee]"
+if [ $(git diff --cached -G "$FORBIDDEN_RE"|wc -l) != 0 ]; then
+    git --no-pager diff --cached -G "$FORBIDDEN_RE"
+    echo
+    echo "ERROR: You're trying to commit a line containing the $FORBIDDEN_RE re"
+    exit 1
 fi
-exit 0  # accept
